---
- name: Run ipconfig on Windows host
  hosts: windows
  gather_facts: no
  tasks:
    - name: Execute ipconfig command
      win_command: ipconfig
      register: ipconfig_output

    - name: Display ipconfig output
      debug:
        var: ipconfig_output.stdout
